version: '3.7'
services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./script:/docker-entrypoint-initdb.d/
      - ./mongo/dump:/db-dump
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - practica_net


  backend_container:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      DB_URI: mongodb://root:example@mongodb:27017/movie
    ports:
      - "8000:8000"
    networks:
      - practica_net

  frontend_container:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend_container
    networks:
      - practica_net


  mongo-express:
    image: mongo-express
    container_name: my_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: usuario
      ME_CONFIG_BASICAUTH_PASSWORD: usuario
    depends_on:
      - mongodb
    networks:
      - practica_net

  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_practica
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - backend_container
    networks:
      - practica_net

  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana_practica
    ports:
      - "3500:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - myGrafanaVol:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - prometheus
    networks:
      - practica_net

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend_container
      - backend_container
    networks:
     - practica_net

networks:
  practica_net:
    name: practica_net
    driver: bridge

volumes:
  mongodb_data:
  myGrafanaVol:
